---
title: "Final Project Option 3"
author: "Parts 3 and 4 Grading Rubric"
output:
  pdf_document: 
  toc: no
urlcolor: blue
---

# Part 3 

## Presentation

- Informative slides **(/20 points)** 
  
  * Each slide should not contain more than three full sentences 
    
  * Slides may contain images, equations, and/or tables 

- Clearly articulated research question **(/10 points)**

  * Make sure the audience knows what was the question that motivated your research 

- Clearly articulated findings and conclusion **(/10 points)**

  * State any questions or criticisms 
  
  * Report any new findings or insights 
  
- Deductions for time over 5 mins 1 point for every 5 seconds over **(-0 points)**

- Deductions for time under 3 mins **(-0 points)**

**Total points for presentation: **




## Paper

- Technical specifications 

  * Page length at least 2 (yes/no)
  
  * Four labeled sections: introduction, description, results, conclusion (yes/no)
  
  * Total deducted points: **-0 points**
  
- Informative introduction **(/10 points)**

  * Must clearly present an overview of the new statistical method including it's usefulness. 
  
  * Describe what type of relationships the method allows one to investigate. 
  
  * Reference a recently published example application of this model as a motivating example. 

- Reflection on the methodology **(/20 points)**

  * Clearly communicate the main idea behind this method including any necessary conditions. 

  * Explain some useful estimates/summaries that can be derived from this model and/or describe which type of visual summaries are useful in applications of this method. 
  
  * Include instructions on how to use this method in R. 

- Discussion and conclusion **(/20 points)**

  * Compare and contrast the method to models that we discussed in class. 

  * Mention any known limitations of the method.  

- References **(/10 points)**

  * Must be cited appropriately throughout the paper. 

  * Each reference must be cited in a way that anyone can find the source. 

  * Must be cited alphabetically. 
  
  * At least three peer-reviewed.
    
**Total points for paper: **

**Total points for Part 3: **

# Part 4