---
title: "Final Project Option 1"
author: "Parts 3 and 4 Grading Rubric"
output:
  pdf_document: 
  toc: no
urlcolor: blue
---


# Part 3

## Presentation

- Informative slides **(/20 points)** 
  
  * Each slide should not contain more than three full sentences 
    
  * Slides may contain images, equations, and/or tables 

- Clearly articulated research question **(/10 points)**

  * Make sure the audience knows what was the question that motivated your research 

- Clearly articulated findings and conclusion **(/10 points)**

  * State any questions or criticisms 
  
  * Report any new findings or insights 
  
- Deductions for time over 5 mins 1 point for every 5 seconds over **(-0 points)**

- Deductions for time under 3 mins **(-0 points)**

**Total points for presentation: **



## Paper


- Technical specifications 

  * Page length at least 2 (yes/no)
  
  * Four labeled sections: introduction, description, results, conclusion (yes/no)
  
  * Total deducted points: **-0 points**

- Informative introduction **(/10 points)**

  * Must demonstrate an understanding of the main research question(s). 

  * Must provide a brief literature review of relevant publications.  

- Thoughtful analysis and reflection on the methodology **(/20 points)**

  * Clearly communicate the main ideas and technical statistical methods used in the main paper. 

  * Relate the statistical methods to the topics we covered in class.  

  * Discuss the appropriateness of various necessary assumptions.

- Statistical discussion and critique **(/20 points)**

  * Present relevant statistical questions that may be a natural extension of the work. 

  * Critique the results of the statistical analysis providing evidence of statistical reasoning. 

- References **(/10 points)**

  * Must be cited appropriately throughout the paper. 

  * Each reference must be cited in a way that anyone can find the source. 

  * Must be cited alphabetically. 
  
  * At least three peer-reviewed.
  
**Total points for paper: **

**Total points for Part 3: **

## Part 4 


Part 4 of your final project represents the peer-review component of your projects. This part of your project is worth 100 points total. You may earn up to 80 points by completing any combination of the following 

- Ask a thoughtful (and non-repetitive) question on another student's presentation (20 points each)

- Respond to a question about your project (20 points each)

- Provide a thoughtful (and non-repetitive) comment or observation on another student's presentation (10 points each, maximum of 4)

- Provide a specific, topic-related compliment to another student's presentation (5 points each, maximum of 4)


The remaining 20 points of this assignment will be assigned based on how well you adhere to the following instructions: 

- Edit your Slack comment sharing your presentation to include the title of your project and the option number for your project; 

- Ask at least one thoughtful (non-repetitive) questions on at least one project from someone who did the same option as you; 

- Comment on at least one project from someone who did a different option than you did; 

- Prioritize commenting on anyone who has not yet received at least two comments; 

- Be respectful and courteous and focus your comments on the content of the work; 

- Make sure your feedback provides indication that you have both watched the recorded presentation and skimed through the written report for any projects you provide with feedback; 

- Submit your comments to other student's projects by 11:59 pm EST on Friday the 14th; 

- Submit your responses to other students' questions/comments by 11:59 pm EST on Sunday the 15th. 