---
title: "Uncovered material"
subtitle: "STAT 021"
author: "Suzanne Thornton"
institute: "Swarthmore College"
date: "updated: `r Sys.Date()`"
output:
  xaringan::moon_reader:
 #   css: ["default", "assets/sydney-fonts.css", "assets/sydney.css"]
    self_contained: false # if true, fonts will be stored locally
#    includes:
 #     in_header: "assets/mathjax-equation-numbers.html"
    nature:
#      beforeInit: ["assets/remark-zoom.js", "https://platform.twitter.com/widgets.js"]
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: '16:9' # alternatives '16:9' or '4:3' or others e.g. 13:9
      navigation:
        scroll: false # disable slide transitions by scrolling
includes:
  in_header: mystyles.sty
---

```{r setup_pres, include=FALSE, echo=FALSE}
#devtools::install_github("ropenscilabs/icon")
#devtools::session_info('rmarkdown')

rm(list=ls())
library('tidyverse')
library('gridExtra')
library('broom')
library('cowplot')

library("RefManageR")
library("DT")


#setwd("~/Google Drive Swat/Swat docs/Stat 21/Class13_files")
#setwd("~/Drive/Swat docs/Stat 21/Class9_files")
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(fig.path='Figs/',echo=TRUE, warning=FALSE, message=FALSE)

```

```{css, echo=FALSE}
pre {
  background: #FFBB33;
  max-width: 100%;
  overflow-x: scroll;
}

.scroll-output {
  height: 75%;
  overflow-y: scroll;
}

.scroll-small {
  height: 50%;
  overflow-y: scroll;
}
   
.red{color: #ce151e;}
.green{color: #26b421;}
.blue{color: #426EF0;}
```


Now suppose we have two categorical predictor variables and one numerical response. We model this with a ANOVA model but since there are two factors, we call it a two-way ANOVA model. (The same is true for three and four-way models, etc.)


- When an interaction effect is present in a two-way ANOVA model, the impact of one categorical variable depends on the level of the other categorical variable.

- When interaction effects are significant, this means that interpretation of the main effects is incomplete or misleading. 


Cell means model: $y_{ijk} = \mu + \tau_i + \gamma_j + (\tau \gamma)_{ij} + \epsilon_{ijk}$ where 
$$i =1,\dots,a \text{;} \quad j=1,\dots,b \text{;} \quad k=1,\dots n$$
and $a$ is the number of groups for the first categorical variable and $b$ is the number of groups for the second categorical variable. 

---
## Interaction terms in a 2-way ANOVA 


Now suppose we have two categorical predictor variables and one numerical response. We model this with a ANOVA model but since there are two factors, we call it a two-way ANOVA model. (The same is true for three and four-way models, etc.)


- When an interaction effect is present in a two-way ANOVA model, the impact of one categorical variable depends on the level of the other categorical variable.

- When interaction effects are significant, this means that interpretation of the main effects is incomplete or misleading. 


--
Recall, when we only have categorical predictor variables, we are typically not just interested in .red[estimation], rather we are interested in an .blue[inferential] question such as: does the average value of the response, $Y$, differ significantly across the different categories of some categorical predictor variable?  

