---
title: "Stat 21 Homework 2 Worksheet"
subtitle: "Problem Solving Strategies" 
output:
  pdf_document: 
    toc: no
  html_document:
    code_folding: show
    toc: yes
    toc_float: yes
urlcolor: blue
---

```{r setup, include=FALSE}
###########################
# DEFAULT SETTINGS
###########################
knitr::opts_chunk$set(message = FALSE) # include this if you don't want markdown to knit messages
knitr::opts_chunk$set(warning = FALSE) # include this if you don't want markdown to knit warnings
knitr::opts_chunk$set(echo=TRUE) # set echo=FALSE to hide code 

###########################
# LIBRARIES
###########################
library(ggplot2)
library(tidyverse)
library(gridExtra)
library(gcookbook)
library(knitr)
```



## Problem 2 

Student's investigating the packaging of potato chips purchased 6 bags of Lay's Ruffles marked with a net weight of 28.3 grams. They carefully weighed the contents of each bag, recording the following weights (in grams): 29.3, 28.2, 29.1, 28.7, 28.9, 28.5 We want to test whether or not the net weight of these chips is different from 28.3 g. 


**What is the unknown population parameter?**

&nbsp;
&nbsp;
&nbsp;

**What is the sample estimate?**

&nbsp;
&nbsp;
&nbsp;

**What is the sampling distribution of the sample estimate?**

&nbsp;
&nbsp;
&nbsp;

**Which procedure should we use?**

&nbsp;
&nbsp;
&nbsp;

**Which assumptions do we need to check?**
&nbsp;
&nbsp;
&nbsp;


## Problem 3 

In a 2017 online Gallup poll of 18620 participants, when asked "Do you share news stories mostly with people who have views similar to your own or mostly with people whose views differ from your own?", $70\%$ of the respondents replied "Similar views" while the other $30\%$ replied "Different views". We want to find a $90\%$ confidence interval for the proportion of all US adults that share new stories with people having the same view as themselves. 


**What is the unknown population parameter?**

&nbsp;
&nbsp;
&nbsp;

**What is the sample estimate?**

&nbsp;
&nbsp;
&nbsp;

**What is the sampling distribution of the sample estimate?**

&nbsp;
&nbsp;
&nbsp;

**Which procedure should we use?**

&nbsp;
&nbsp;
&nbsp;

**Which assumptions do we need to check?**
&nbsp;
&nbsp;
&nbsp;

\pagebreak

## Problem 4 

The College Board reported that $60\%$ of all students who took the 2004 AP Statistics exam earned scores of 3 or higher. One teacher wondered if the performance of her school was different. She believed that year's students to by typical of those who will take AP Stats at her school and was pleased when $65\%$ of her 54 students achieved scores of 3 or better. We want to assess her claim that her school is different with either a confidence interval or a hypothesis test. 


**What is the unknown population parameter?**

&nbsp;
&nbsp;
&nbsp;

**What is the sample estimate?**

&nbsp;
&nbsp;
&nbsp;

**What is the sampling distribution of the sample estimate?**

&nbsp;
&nbsp;
&nbsp;

**Which procedure should we use?**

&nbsp;
&nbsp;
&nbsp;

**Which assumptions do we need to check?**
&nbsp;
&nbsp;
&nbsp;


## Problem 6 

American League baseball teams play their games with the designated hitter rule, meaning that pitchers do not bat. The league believes that replacing the pitcher, traditionally a weak hitter, with another player in the batting order produces more runs and generates more interest among fans. Below are the average numbers of runs score in American League and National League stadiums for the first half of the 2001 season. 

**American:** 11.1, 10.8, 10.8, 10.3, 10.3, 10.1,10.0, 9.5, 9.4, 9.3, 9.2, 9.2, 9.0, 8.3

**National:** 14.0, 11.6, 10.4, 10.3, 10.2, 9.5, 9.5, 9.5, 9.5, 9.1, 8.8, 8.4, 8.3, 8.2, 8.1, 7.9 

We want to determine if the 14 runs scored per game at Coors is unusual but we do not want to use two separate confidence intervals to determine whether the two leagues differ in average number of runs scored. 


**What is the unknown population parameter?**

&nbsp;
&nbsp;
&nbsp;

**What is the sample estimate?**

&nbsp;
&nbsp;
&nbsp;

**What is the sampling distribution of the sample estimate?**

&nbsp;
&nbsp;
&nbsp;

**Which procedure should we use?**

&nbsp;
&nbsp;
&nbsp;

**Which assumptions do we need to check?**
&nbsp;
&nbsp;
&nbsp;

\pagebreak

## Problem 7 

Having done poorly on their Biology final exams in June, six students repeat the course in summer school and take another exam in August. If we consider these students to be representative of all students who might attend this summer school in other years, how can we determine if these results provide evidence that the program is worthwhile? 

**Person:** Aaron, Brittney, Chloe, Drake, Edward, Frankie

**June scores:** 54, 49, 68, 66, 62, 62  

**August scores:** 50, 65, 74, 64, 68, 72


**What is the unknown population parameter?**

&nbsp;
&nbsp;
&nbsp;

**What is the sample estimate?**

&nbsp;
&nbsp;
&nbsp;

**What is the sampling distribution of the sample estimate?**

&nbsp;
&nbsp;
&nbsp;

**Which procedure should we use?**

&nbsp;
&nbsp;
&nbsp;

**Which assumptions do we need to check?**
&nbsp;
&nbsp;
&nbsp;


## Problem 9 

A survey of $430$ randomly chosen college students found that $21\%$ of the 222 full-time students and $18\%$ of the 208 part-time students had purchased books in person from their campus book store. We want to determine if there is sufficient statistical evidence that full-time students are more likely than part-time students to purchase their books in person (rather than online)? 


**What is the unknown population parameter?**

&nbsp;
&nbsp;
&nbsp;

**What is the sample estimate?**

&nbsp;
&nbsp;
&nbsp;

**What is the sampling distribution of the sample estimate?**

&nbsp;
&nbsp;
&nbsp;

**Which procedure should we use?**

&nbsp;
&nbsp;
&nbsp;

**Which assumptions do we need to check?**
&nbsp;
&nbsp;
&nbsp;